---
- hosts: node00
  tasks:
    - cron:
        name: Clear Lastlog
        job: echo “” > /var/log/lastlog
        minute: "0"
        hour: "0"
    
    # Delete cronjob
    - cron:
        name: "Check Memory"
        state: absent

    # using secpical time
    - cron:
        name: "Clean up tmp"
        job: "rm -rf /tmp/*"
        special_time: reboot
