---
- hosts: node00
  tasks:
    - cron:
        name: Clear Lastlog
        job: echo “” > /var/log/lastlog
        minute: "0"
        hour: "0"
    
    # Delete cronjob
    - cron:
        name: "Check Memory"
        state: absent

    # using secpical time
    - cron:
        name: "Clean up tmp"
        job: "rm -rf /tmp/*"
        special_time: reboot

    # Weekday and cron_file
    - cron:
        name: yum update
        user: root 
        job: "yum update -y"
        hour: "8"
        minute: "5"
        weekday: "0"
        cron_file: ansible_yum
