---
- hosts: all
  tasks:
    - group:
        name: admin
        state: present

    - user:
        name: admin
        group: admin
        uid: 2048
        expires: 1840897608000
        comment: "Full Name"
