---
- name: check host name
  hosts: all
  tasks:
    - command: "/bin/hostname"
      register: host_name

    - command: "/usr/bin/needs-restarting"
      register: need_reboot
    
    - debug:
        msg: 
          - "Hostname: {{ host_name.stdout }}"
          - "Server need reboot {{need_reboot.rc }}"

