---
- hosts: web1
  tasks:
    - package: name=nginx state=installed
    - service: name=nginx state=started enabled=true
    - unarchive:
        src: /root/nginx.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - replace:
        path: /usr/share/nginx/html/index.html
        regexp: 'This is sample html code'
        replace: 'This is Ansible lab'
